# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: luma
email: info@lumaproject.com
description: "The Luma Project is a multi-purpose campus in the Dominican Republic.\n\n
Our mission is to advance education, technology adoption and innovations in the country and Latin America."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.lumaproject.com" # the base hostname & protocol for your site

videos:
  - kmmSN10Db6Y
  - a9s1VY3HtUg

# Build settings
markdown: kramdown
sass:
  style: :compressed
