# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: luma
email: your-email@domain.com
description: >
  Luma project description
baseurl: "/lumaproject" # the subpath of your site, e.g. /blog
url: "https://korbin.github.io" # the base hostname & protocol for your site

videos:
  - kmmSN10Db6Y
  - a9s1VY3HtUg

# Build settings
markdown: kramdown
sass:
  style: :compressed
